export const GET_LAUNCHES_LOADING = `GET_LAUNCHES_LOADING`;
export const GET_LAUNCHES_SUCCESS = `GET_LAUNCHES_SUCCESS`;
export const GET_LAUNCHES_ERROR = `GET_LAUNCHES_ERROR`;
export const UPDATE_FILTER_LAUNCHYEAR = `UPDATE_FILTER_LAUNCHYEAR`;
export const UPDATE_FILTER_LAUNCHSUCCESS = `UPDATE_FILTER_LAUNCHSUCCESS`;
export const UPDATE_FILTER_LANDSUCCESS = `UPDATE_FILTER_LANDSUCCESS`;
